### ISSUE TITLE
同为群晖我要怎么安装

### ISSUE THREAD

**Issue by bao3** [real-zony/AliDDNSNet#1]
终于找到一个同样用群晖的人写得 aliddns，不过我从 Release 里不清楚我应该使用哪个，直接用 Linux 的来运行吗？还是说要自己弄好 Docker 然后下载  .NetCore 再运行 Linux 版本？

**Comment by real-zony** [comment]
@bao3 你好，请直接下载 Linux 包，也就是 30 多 MB 那个，将其存放在你群晖服务器里面，使用 WINSCP 连上你的群晖 NAS 将这些文件上传上去即可，然后执行在包含 AliDDNSNet 文件的目录执行以下命令
```
./AliDDNSNet
```
即可。

**Comment by real-zony** [comment]
@bao3 当然，参照 Readme 文档，你应该将 settings.json.example 文件的名字更改为 settings.json，并且参照文档配置好这些参数，运行程序即可，然后再群晖的控制面板使用计划任务来定时更新你的 IP 。
![a1](https://user-images.githubusercontent.com/3907132/43116947-dd3a4308-8f3c-11e8-892f-be7b97e4158c.png)
![tim 20180724122606](https://user-images.githubusercontent.com/3907132/43116948-dd987586-8f3c-11e8-815a-d575128d9f70.png)

**Comment by real-zony** [comment]
如果没有其他问题，我就先将此问题关闭。

**Comment by bao3** [comment]
已经弄好了，感谢。
