### ISSUE TITLE
多域名修改

### ISSUE THREAD

**Issue by ZBrettonYe** [real-zony/AliDDNSNet#4]
如果一次要修改多个域名/ 子域名， 这应该怎么写？

**Comment by ZBrettonYe** [comment]
如果要把ip解析到主域名 example.com , 子域名该怎么写？

**Comment by real-zony** [comment]
@ZBrettonYe  你的意思是一次更改多个 IP 对应的域名么？

**Comment by ZBrettonYe** [comment]
是的，其中包含 xxxx.com

**Comment by real-zony** [comment]
如果是这样的话，当前版本并不支持哦，这个特性可以放在下一个里程碑实现。
当然如果你希望为项目贡献代码的话，欢迎 PR 。
