### ISSUE TITLE
linux-x64.zip

### ISSUE THREAD

**Issue by LI-XIAOYAO** [real-zony/AliDDNSNet#5]

**Comment by real-zony** [comment]
@LI-XIAOYAO 有提示什么信息么？

**Comment by LI-XIAOYAO** [comment]
> @LI-XIAOYAO 有提示什么信息么？

**Comment by LI-XIAOYAO** [comment]
./AliDDNSNet: line 2: syntax error: unexpected word (expecting ")") 是不支持吗

**Comment by real-zony** [comment]
可能是目标编译平台的原因，我这边重新编译一个新的二进制文件，之后你再试试。

**Comment by real-zony** [comment]
@LI-XIAOYAO 请尝试 https://github.com/GameBelial/AliDDNSNet/releases/tag/v0.0.2 的 ARM 版本。
