### ISSUE TITLE
请问一下直接使用release中二进制发布版本win-arm与win的区别，以及环境依赖

### ISSUE THREAD

**Issue by NickNameIsNull** [real-zony/AliDDNSNet#7]
请问release中win-arm与win的区别是什么？
运行的环境依赖有什么要求？
比如.NET Framework的版本有要求吗？
.Net Core2.0是否需要安装？

**Comment by real-zony** [comment]
区别主要是 CPU 指令集，因为 Windows 10 是有 ARM 版本的，目前项目是基于 .NET Core 3.1 进行构建。
